name: Validate with HACS

on:
  push:
    branches: [ main ] # Or your default branch
  pull_request:
    branches: [ main ] # Or your default branch

jobs:
  validate:
    name: Validate Repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: HACS Validation
        uses: hacs/action@main
        with:
          category: plugin
          # Optional: If your repository name doesn't match the integration ID
          # integration_id: range-slider-card
